### ISSUE TITLE
Cannot access stock because you do not have any shops!

### ISSUE THREAD

**Issue by xenoflot** [Beez0r/iShop#1]
Hi,

I installed the plugin just now, thanks. I've been conducting testing with two accounts, one has OP, the other doesn't. 
I placed a barrel and a composter and created a shop with the non-OP. I then deleted the shop with /shop delete but now I can't destroy the composter, with either account, even in creative mode.
Both accounts show no shops.

This may result from interaction with GriefPrevention but I figure that an OP should be able to clean things up. Can't spot any commands on the spigot page that might be relevant.

Cheers

**Comment by Beez0r** [comment]
Hi,

Thank you for the report! Are you sneaking (holding shift) when trying to destroy the composter? That is the only way to destroy stock blocks and no permissions are required to destroy it.

Please let me know if this fixes your issue!

**Comment by Beez0r** [comment]
I will assume this issue has been solved. If not, feel free to reply and reopen.

**Comment by xenoflot** [comment]
Oh hi, I got the original notification of "I'll take a look and will update" so was waiting for further news. Github didn't email me when you edited with a question! I'll reinstall the plugin and see how we go. Thanks.
