### ISSUE TITLE
range limit to prevent the shops being used as an ender chest

### ISSUE THREAD

**Issue by piostaet** [Beez0r/iShop#10]
**Plugin Version and Minecraft Version**:
2.12, 1.16.4

**Request**:
 It would be nice if there would be a range limit to restock shops.

**Reason**:
currently its possible to basically use the storage space for shops as a large ender chest or inventory space with easy accessability.

**Comment by senseiwells** [comment]
You can remove the stock block and only allow players to restock through the shop GUI.
Alternatively you could make the stock block a block that is unobtainable in survival (structure block, jigsaw block, etc.) and have stock blocks only in certain locations around the map.

**Comment by senseiwells** [comment]
I believe the author is also working on an update that will prevent players from storing items that they aren't selling in stock but this has a workaround of the player just putting said item for sale and then storing it.

**Comment by piostaet** [comment]
thanks, I'm using it as a workaround for now.

**Comment by Beez0r** [comment]
I will try to figure out some sort of range limit for stock blocks relative to shops the player owns for the next update.

senseiwells has great suggestions that will help out until then!



> 
> 
> You can remove the stock block and only allow players to restock through the shop GUI.
> Alternatively you could make the stock block a block that is unobtainable in survival (structure block, jigsaw block, etc.) and have stock blocks only in certain locations around the map.

**Comment by Beez0r** [comment]
Feature request has been added to updated iShop version 2.13 -- https://www.spigotmc.org/resources/ishop.84555/update?update=394068
