### ISSUE TITLE
BreakShop

### ISSUE THREAD

**Issue by dinobossytnew** [Beez0r/iShop#13]
**Plugin Version and Minecraft Version**:
 ISHOP 2.14 MINECRAFT 1.16.5

**Request**:
 To function that with explosions breaks the store of the players with tnt or crepper explosions and releases items if you have them.
The administrators do not.

**Reason**:
 My server blocks or houses can be stolen with explosives and the plugin creates a system of tardeos where they can change items steal or break their houses with tnt if you raidean so with tnt break the stores where they can have ores or c4 or weapons because they can not and users use it as a bug to take advantage of that can not be broken if you are not the owner.

**Additional Context**:

not

**Comment by Beez0r** [comment]
So in short summary, are you feature requesting shops drop stock inventory item contents upon explosion?
