### ISSUE TITLE
Is there any ways to destroy shop from console ?

### ISSUE THREAD

**Issue by hakunamatata** [Beez0r/iShop#14]
**Plugin Version and Minecraft Version**:

LATEST
**Request**:

when I run shop deleteid <id> from console, it told me that commands can only be performed from user

**Reason**:

but me as an admin wouldn't be always online,  so I want to make 'tricks' to delete shop from console, 
any suggestions ?
**Additional Context**:

**Comment by Beez0r** [comment]
Beta download & changes can be found in our discord server
