### ISSUE TITLE
ItemsAdder

### ISSUE THREAD

**Issue by ddman1211** [Beez0r/iShop#15]
**Plugin Version and Minecraft Version**:
2.20, 1.19.2

**Request**:
 Could you add support for itemsadder?

**Reason**:
When I add itemsadder to sell using your plugin you don't see the 3d model or check it you see it as a normal minecraft item.

**Additional Context**:
If you want to make it easier to use itemsadder in your plugin you can use nbtapi as ssomar did to add support for itemsadder in his plugin called ExecutableItems.

**Comment by ddman1211** [comment]
Could you also add support for itemFramel to be used as a store ?
and I will place 3d to the blocks of the store example in material we put: itemsadder:machine:machine_1

this works like this itemsadder: //reference to the plugin
the next argument called machinadespachadora would be the one that mentions the folder or file of items_packs.
The last argument that refers to the item or material in itemsadder would be machine_1 which is the name given to that object in itemsadder.

**Comment by ddman1211** [comment]
https://github.com/HibiscusMC/HMCCosmetics/blob/master/common/src/main/java/io/github/fisher2911/hmccosmetics/hook/item/ItemsAdderHook.java 
example

**Comment by ddman1211** [comment]
https://github.com/LoneDev6/API-ItemsAdder

**Comment by Beez0r** [comment]
ItemsAdder is a premium plugin, costing $19.95 EUR to purchase, which I will not buy.

iShop is free and will only support free open-source plugins that are popular and have demand for becoming a soft-dependency.

**Comment by dinobossytnew** [comment]
Hello I am also interested, if you want to pass me your discord and I give you a copy of the plugin that I buy because lone gives permissions to give a .jar of the plugin if it is to add support to the plugin and not use it on servers.

**Comment by Beez0r** [comment]
Sorry, but because ItemsAdder plugin is premium and not open source I cannot use it or maintain updates
