### ISSUE TITLE
Shop create does not recognize a barrel if there is item frame on it. 

### ISSUE THREAD

**Issue by davidolos** [Beez0r/iShop#4]
Bug: My players got used to placing item frames on barrel and then use /shop create.  It worked in the old plugin version.

How to reproduce : Place item on barrel, use /shop create on it. It will say "Targeted block must match set shop block!"

Idea : Maybe you can add a choice to config to switch between targeting, which is new in this version and clicking, which was in the old ver. 
Or maybe you can try adding some function that will allow player to place item frames on it. 

Thanks a lot!

**Comment by Beez0r** [comment]
I have fixed the targeted block issue in the next version that will be released today! I will close this issue when my commits are pushed

**Comment by Beez0r** [comment]
This has been fixed in 4feada88e48b2e0a19f73f0d472db4bf97934d1b

Version 2.6 will be released shortly! Thanks for the report
