### ISSUE TITLE
Shop migration from old plugin was unsuccessful

### ISSUE THREAD

**Issue by davidolos** [Beez0r/iShop#5]
Hi there.

I was recently trying to implement Ishop, but i had issue. Shops dissapeared so i suggest that shop migration was unsuccessful. I even tried to copy shop .db file to ishop folder, but with no luck, it was still gone.

So i turned on the old trading shop back again, and the shops are there. I will wait for your response before i force my players to empty their shop stocks and recreate all shop once again. Thank you.

**Comment by Beez0r** [comment]
Hello!

Shops will be able to migrate from any TradingShops version. I recommend downloading iShop.jar file from the spigot resource page [https://www.spigotmc.org/resources/ishop.84555/](url), start the server and let the new config.yml generate and an empty database. Shutdown the server, then delete the newly generated shops.db database and replace it with your original TradingShops database. Now start up the server again.

The only reason the old database would not work is if you are using an old configuration file from TradingShops, as only iShop config.yml will work.

**Comment by Beez0r** [comment]
If it still does not work after attempting with newly release version 2.6, please attach your database and config.yml file so I can take a look and try to solve this issue!

**Comment by Beez0r** [comment]
If it still does not work after attempting with newly released version 2.6, please attach your database and config.yml file (or I can give you my email address to send it to) so I can take a look and try to solve this issue!

**Comment by davidolos** [comment]
Hello!

I tried to update ishop and migrate old db.  I did everything as you said (generate new config yml from ishop, restart, add old shop.db file, restart) And its still doesnt here.
[ishop.zip](https://github.com/Beez0r/iShop/files/5463492/ishop.zip)
I am sending my ishop config (altough its default) and shop db from trading files. 
Thank you!

**Comment by Beez0r** [comment]
There are no saved shop trades in the shops.db file sent. Stock and shop locations are present, but no rows of trading.

Do you have any backups of database file I can look at that has shop trades?

**Comment by davidolos** [comment]
I dont have any else. 

If i turn on old tradingshop with this db. file, it works just fine. So i dont know, where is the issue.

**Comment by Beez0r** [comment]
Please send working tradingshops plugin folder zip

**Comment by davidolos** [comment]
[TradingShops.zip](https://github.com/Beez0r/iShop/files/5464257/TradingShops.zip)

If you have discord, we can meet there and i can show it on my server for you.

**Comment by Beez0r** [comment]
The database for last zip file you sent has shop trades, so I used that shops.db file and it worked in my iShop server

Yes my discord is Beez0r 0001

**Comment by davidolos** [comment]
Resolved. I used older version of minecraft (1.16.2) - after 1.16.4 update it works just fine.
