### ISSUE TITLE
Chests are able to be blown up by TNT

### ISSUE THREAD

**Issue by ChiboYen** [Beez0r/iShop#7]
Chests are able to be blown up by TNT, and while the shop itself is there, it is an issue as you cannot access it without placing a new chest down in the exact location where the shop originally was. A chest should not be able to be blown up by TNT.

I realize I am using a chest as a shop block, but this bug can be applied to any shop block.

**Comment by Beez0r** [comment]
I will work on this fix and add to next plugin update

**Comment by Beez0r** [comment]
Version 2.8 officially released -- https://www.spigotmc.org/resources/ishop.84555/
